# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Check if ssh-agent is already running under your user
if ! ps -ef | grep -v "grep" | grep -q "ssh-agent"; then
    eval $(ssh-agent -s)
fi
